"""H1.2.5: tabla instrumento_broker_mapping para mapeo Argo a brokers

Revision ID: 056f2b857204
Revises: 9c62f61fa821
Create Date: 2026-05-21 18:40:12.492321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '056f2b857204'
down_revision: Union[str, Sequence[str], None] = '9c62f61fa821'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instrumento_broker_mapping',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instrumento_id', sa.Integer(), nullable=False),
    sa.Column('broker', sa.String(length=20), nullable=False),
    sa.Column('symbol_externo', sa.String(length=80), nullable=False),
    sa.Column('moneda_liquidacion', sa.String(length=15), nullable=False),
    sa.Column('plazo', sa.String(length=10), nullable=False),
    sa.Column('es_default', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('fecha_validacion', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instrumento_id'], ['instrumentos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('broker', 'symbol_externo', 'plazo', name='uq_broker_symbol_plazo')
    )
    op.create_index('ix_inst_broker_default', 'instrumento_broker_mapping', ['instrumento_id', 'broker', 'es_default'], unique=False)
    op.create_index(op.f('ix_instrumento_broker_mapping_broker'), 'instrumento_broker_mapping', ['broker'], unique=False)
    op.create_index(op.f('ix_instrumento_broker_mapping_instrumento_id'), 'instrumento_broker_mapping', ['instrumento_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_instrumento_broker_mapping_instrumento_id'), table_name='instrumento_broker_mapping')
    op.drop_index(op.f('ix_instrumento_broker_mapping_broker'), table_name='instrumento_broker_mapping')
    op.drop_index('ix_inst_broker_default', table_name='instrumento_broker_mapping')
    op.drop_table('instrumento_broker_mapping')
    # ### end Alembic commands ###
