"""H1.2.5: agregar columna segmento a instrumento_broker_mapping

Revision ID: 120cc791cc97
Revises: 056f2b857204
Create Date: 2026-05-24 09:02:28.636329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '120cc791cc97'
down_revision: Union[str, Sequence[str], None] = '056f2b857204'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instrumento_broker_mapping', sa.Column('segmento', sa.String(length=20), nullable=False, server_default='MERV'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instrumento_broker_mapping', 'segmento')
    # ### end Alembic commands ###
