"""feat(schema): tabla ticks_crudos para market data crudo (H1.2.4)

Revision ID: 68eb9caf94d6
Revises: 120cc791cc97
Create Date: 2026-06-03 18:14:05.755613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68eb9caf94d6'
down_revision: Union[str, Sequence[str], None] = '120cc791cc97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticks_crudos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mapping_id', sa.Integer(), nullable=False),
    sa.Column('ts_mensaje', sa.DateTime(), nullable=False),
    sa.Column('ts_recepcion', sa.DateTime(), nullable=False),
    sa.Column('ts_ultimo_trade', sa.DateTime(), nullable=True),
    sa.Column('bid_price', sa.Float(), nullable=True),
    sa.Column('bid_size', sa.Integer(), nullable=True),
    sa.Column('offer_price', sa.Float(), nullable=True),
    sa.Column('offer_size', sa.Integer(), nullable=True),
    sa.Column('last_price', sa.Float(), nullable=True),
    sa.Column('last_size', sa.Integer(), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['mapping_id'], ['instrumento_broker_mapping.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ticks_crudos_mapping_ts', 'ticks_crudos', ['mapping_id', 'ts_mensaje'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ticks_crudos_mapping_ts', table_name='ticks_crudos')
    op.drop_table('ticks_crudos')
    # ### end Alembic commands ###
