"""schema inicial: 5 tablas con UniqueConstraint compuesto en instrumentos (ticker + mercado)

Revision ID: 9c62f61fa821
Revises: 
Create Date: 2026-05-19 19:18:37.518470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c62f61fa821'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instrumentos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('mercado', sa.String(length=30), nullable=False),
    sa.Column('moneda', sa.String(length=20), nullable=False),
    sa.Column('fuente', sa.String(length=30), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'mercado', name='uq_instrumento_ticker_mercado')
    )
    op.create_index(op.f('ix_instrumentos_ticker'), 'instrumentos', ['ticker'], unique=False)
    op.create_table('log_collectors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('collector', sa.String(length=30), nullable=False),
    sa.Column('timestamp_inicio', sa.DateTime(), nullable=False),
    sa.Column('timestamp_fin', sa.DateTime(), nullable=True),
    sa.Column('instrumentos_procesados', sa.Integer(), nullable=False),
    sa.Column('instrumentos_exitosos', sa.Integer(), nullable=False),
    sa.Column('instrumentos_fallidos', sa.Integer(), nullable=False),
    sa.Column('filas_insertadas', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('errores_json', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_collectors_collector'), 'log_collectors', ['collector'], unique=False)
    op.create_index('ix_logcol_collector_inicio_desc', 'log_collectors', ['collector', 'timestamp_inicio'], unique=False)
    op.create_index('ix_logcol_estado', 'log_collectors', ['estado'], unique=False)
    op.create_table('macro_indicadores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('indicador', sa.String(length=50), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('unidad', sa.String(length=30), nullable=False),
    sa.Column('fuente', sa.String(length=30), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('indicador', 'fecha', name='uq_macro_indicador_fecha')
    )
    op.create_index('ix_macro_indicador_fecha_desc', 'macro_indicadores', ['indicador', 'fecha'], unique=False)
    op.create_index(op.f('ix_macro_indicadores_indicador'), 'macro_indicadores', ['indicador'], unique=False)
    op.create_table('cotizaciones_1min',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instrumento_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('volume_dolarizado', sa.Float(), nullable=True),
    sa.Column('cantidad_operaciones', sa.Integer(), nullable=True),
    sa.Column('fuente', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instrumento_id'], ['instrumentos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrumento_id', 'timestamp', name='uq_cot1min_instr_ts')
    )
    op.create_index('ix_cot1min_instr_ts_desc', 'cotizaciones_1min', ['instrumento_id', 'timestamp'], unique=False)
    op.create_index('ix_cot1min_timestamp', 'cotizaciones_1min', ['timestamp'], unique=False)
    op.create_table('cotizaciones_diarias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instrumento_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('volume_dolarizado', sa.Float(), nullable=True),
    sa.Column('cantidad_operaciones', sa.Integer(), nullable=True),
    sa.Column('fuente', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instrumento_id'], ['instrumentos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrumento_id', 'fecha', name='uq_cotdiaria_instr_fecha')
    )
    op.create_index('ix_cotdiaria_fecha', 'cotizaciones_diarias', ['fecha'], unique=False)
    op.create_index('ix_cotdiaria_instr_fecha_desc', 'cotizaciones_diarias', ['instrumento_id', 'fecha'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cotdiaria_instr_fecha_desc', table_name='cotizaciones_diarias')
    op.drop_index('ix_cotdiaria_fecha', table_name='cotizaciones_diarias')
    op.drop_table('cotizaciones_diarias')
    op.drop_index('ix_cot1min_timestamp', table_name='cotizaciones_1min')
    op.drop_index('ix_cot1min_instr_ts_desc', table_name='cotizaciones_1min')
    op.drop_table('cotizaciones_1min')
    op.drop_index(op.f('ix_macro_indicadores_indicador'), table_name='macro_indicadores')
    op.drop_index('ix_macro_indicador_fecha_desc', table_name='macro_indicadores')
    op.drop_table('macro_indicadores')
    op.drop_index('ix_logcol_estado', table_name='log_collectors')
    op.drop_index('ix_logcol_collector_inicio_desc', table_name='log_collectors')
    op.drop_index(op.f('ix_log_collectors_collector'), table_name='log_collectors')
    op.drop_table('log_collectors')
    op.drop_index(op.f('ix_instrumentos_ticker'), table_name='instrumentos')
    op.drop_table('instrumentos')
    # ### end Alembic commands ###
